export default [
  {
    name: 'PaperX',
    description: 'Aprendizado por exercícios para vestibulandos e concurseiros',
    market: 'B2B',
    'last-round': 'Vendida para o Descomplica',
    status: 'Saída',
    site: 'https://paperx.com.br',
    logo: 'paperx.png',
  },
  {
    name: 'Liber',
    description: 'Marketplace de aulas particulares com tutores selecionados',
    market: 'B2C',
    'last-round': 'Seed Capital',
    status: 'Operação',
    site: 'https://liberedu.com.br',
    logo: 'liber.png',
  },
  {
    name: 'Jovens Gênios',
    description: 'Plataforma de aprendizado adaptativo e gamificado de matemática (6˚ a 9˚ ano do EF2)',
    market: 'B2B',
    'last-round': 'Seed Capital',
    status: 'Operação',
    site: 'https://jovensgenios.com',
    logo: 'jg.png',
  },
  {
    name: 'FFAC',
    description: 'Investimento em educação através de venda de artigos esportivos utilizados por jogadores',
    market: 'B2B2C',
    'last-round': 'Pre-seed Capital',
    status: 'Validação',
    site: 'https://footballforacause.com.br',
    logo: 'FFAC.png',
  },
  {
    name: 'Árvore de Livros',
    description: 'Plataforma de leitura digital para escolas',
    market: 'B2B',
    'last-round': 'Fusão',
    status: 'Escala',
    site: 'https://arvoredelivros.com.br',
    logo: 'arvore.png',
  },
  {
    name: 'Barkus',
    description: 'Metodologia de aprendizado de educação financeira',
    market: 'B2C e B2B',
    'last-round': 'Seed Capital',
    status: 'Operação',
    site: 'https://barkus.com.br/site/',
    logo: 'barkus.png',
  },
  {
    name: 'Voa Educação',
    description: 'Gestão de desenvolvimento de competência socioemocional',
    market: 'B2B',
    'last-round': 'Seed Capital',
    status: 'Operação',
    site: 'https://voaed.com.br',
    logo: 'voa.png',
  },
  {
    name: 'Lecionas',
    description: 'Banco de questões inteligente para professores (6˚ a 9˚ ano do EF2)',
    market: 'B2C',
    'last-round': 'Seed Capital',
    status: 'Validação',
    site: 'http://lecionas.com.br',
    logo: 'lecionas.png',
  },
  {
    name: 'Cody Academic',
    description: 'Ensino de pensamento computacional para crianças e adolescentes',
    market: 'B2B2C',
    'last-round': 'Pre-seed Capital',
    status: 'Operação',
    site: 'https://codyacademic.com.br',
    logo: 'cody.png',
  },
  {
    name: 'FazGame',
    description: 'Desenvolvimento de produção textual e criatividade através de criação de jogos',
    market: 'B2B',
    'last-round': 'Seed Capital',
    status: 'Operação',
    site: 'https://www.fazgame.com.br/',
    logo: 'faz.png',
  },
  {
    name: 'Comuny',
    description: 'Plataforma de compartilhamento de livros usados',
    market: 'B2B2C',
    'last-round': 'Seed Capital',
    status: 'Validação',
    site: 'https://www.comuny.com.br/#/',
    logo: 'comuny.png',
  },
  {
    name: 'Elfus',
    description: 'Marketplace de produção de conteúdo EAD',
    market: 'B2B',
    'last-round': 'Fusão',
    status: 'Operação',
    site: 'https://www.el4us.com/',
    logo: 'elfus.png',
  },
  {
    name: 'VIS',
    description: 'Plataforma para produção de conteúdo em realidade virtual por professores',
    market: 'B2B',
    'last-round': 'Seed Capital',
    status: 'Validação',
    site: 'https://www.virtualimmersiveschool.com/',
    logo: 'vis.png',
  },
  {
    name: 'Tullli',
    description: 'Sistema inteligente de gestão escolar',
    market: 'B2B',
    'last-round': 'Seed Capital',
    status: 'Operação',
    site: 'https://tullli.com/',
    logo: 'tullli.png',
  },
  {
    name: 'Bela Horta',
    description: 'Educação ambiental, alimentar e cultura maker através de cuidado de horta',
    market: 'B2B',
    'last-round': 'Pre-seed Capital',
    status: 'Prototipação',
    site: 'https://www.belahorta.me/',
    logo: 'bh.png',
  },
  {
    name: 'Soluções XR',
    description: 'Produção de conteúdo em realidade aumentada com auxílio de IA a partir de material didático prévio',
    market: 'B2B',
    'last-round': 'Pre-seed Capital',
    status: 'Prototipação',
    site: 'https://www.instagram.com/solucoesxr/',
    logo: 'xr.png',
  },
];
